### PR TITLE
add custom font option

### PR DESCRIPTION
**Pull request by hamdiwanis**

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
I'm so curious to see what you've added but it's almost impossible using the [files tab](https://github.com/EddyVerbruggen/nativescript-feedback/pull/23/files) because you changed the indentation from 2 to 4 spaces. Can you perhaps go back to 2 and push it to your master branch?

**Comment by hamdiwanis** [comment]
sure, sorry for that it's the IDE's fault :D, thanks for the response but i think some other format changes still an issue

**Comment by hamdiwanis** [comment]
will try over later without messing things up this time :)

**Comment by EddyVerbruggen** [comment]
Yeah your IDE has a will of its own 🤣
Those spaces in `< any >` below are not ideal, if you can remove superfluous spaces like that then I'll happily review and merge it:

screen shot 2018-05-31 at 22 14 32

**Comment by hamdiwanis** [comment]
i updated it :)

**Comment by EddyVerbruggen** [comment]
Super, thank you! 💯

I'll test this and probably add a note about where the dev should put the font.

**Comment by hamdiwanis** [comment]
thanks, also after you test it. there is an open issue asking for this feature i think may be closed :)
https://github.com/EddyVerbruggen/nativescript-feedback/issues/9

**Pull request merged**
