### PR TITLE
Update tapadoo and allow bottom position in android

### LINKED ISSUE #35: android.view.InflateException
Hello, I am getting `android.view.InflateException` when calling show on response from a promise.  Seems to be related to an older version of tapadoo alerter [https://github.com/Tapadoo/Alerter/issues/145](issue). Is it possible to upgrade to the most recent tapadoo alerter to fix this problem?

### PR DESCRIPTION
**Pull request by dosomder**
Fixes https://github.com/EddyVerbruggen/nativescript-feedback/issues/35 and probably https://github.com/EddyVerbruggen/nativescript-feedback/issues/61

### CODE REVIEW

**Comment by dosomder** [comment]
@EddyVerbruggen Is there anything else needed?

**Comment by EddyVerbruggen** [comment]
@dosomder Yeah, time to review ;)
Thanks for the PR - I hope to get to this soon!

**Comment by dosomder** [comment]
@EddyVerbruggen it's been 2 weeks. Any news?

**Comment by EddyVerbruggen** [comment]
You PR works like a boss, thanks a lot on behalf of anyone needing it.

Version 1.4.0 is now up on npm.

**Pull request merged**
